<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWCakeOu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWCakeOu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWCakeOu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWCakeOu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWCakeOu\App_KernelDevDebugContainer([
    'container.build_hash' => 'WCakeOu',
    'container.build_id' => '9784dfaf',
    'container.build_time' => 1642512310,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWCakeOu');
